/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RapidAmbulanceWlList {
    }
}
declare global {
    interface HTMLRapidAmbulanceWlListElement extends Components.RapidAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLRapidAmbulanceWlListElement: {
        prototype: HTMLRapidAmbulanceWlListElement;
        new (): HTMLRapidAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "rapid-ambulance-wl-list": HTMLRapidAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface RapidAmbulanceWlList {
    }
    interface IntrinsicElements {
        "rapid-ambulance-wl-list": RapidAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rapid-ambulance-wl-list": LocalJSX.RapidAmbulanceWlList & JSXBase.HTMLAttributes<HTMLRapidAmbulanceWlListElement>;
        }
    }
}
